Variables: 2 tasks from 1 lesson on JS
limur88/automation_js-aqa_AV pull request #1
Opened 2024-05-23 04:28 UTC by limur88

2024-05-23 04:39 UTC, shnobel approved these changes, later dismissed

2024-05-23 04:40 UTC, shnobel commented on Variables/task1.js
> +console.log('item_7 == ' + item_7);
consider to use string interpolation 
console.log(`item_7 == ${item_7}`)

2024-05-23 14:07 UTC, limur88 commented
@anatoly-karpovich @VladimirLQA

2024-05-23 14:07 UTC, limur88 commented
@limur88

2024-05-23 20:18 UTC, anatoly-karpovich reviewed
Change let to const in task 2 and 3.

And good job!

2024-05-23 20:18 UTC, anatoly-karpovich commented on Variables/task2.js
> +let secondDiscriminant = (-4) ** 2 - 4 * (-5);
I belive this-like variables should be created with const, check task 2/3

2024-05-23 20:18 UTC, anatoly-karpovich approved these changes, later dismissed

2024-05-24 18:33 UTC, anatoly-karpovich requested changes

2024-05-24 18:33 UTC, anatoly-karpovich commented on Variables/task3.js
> +let second = String(number) + number;
Prompt returns string value, so additional conversation to string is not required

2024-05-24 18:33 UTC, anatoly-karpovich commented on Variables/task3.js
> +let sum = digit + (+ secondAdditive) + (+ thirdAdditive);
For variables than won't be changed use const

2024-05-24 18:52 UTC, anatoly-karpovich approved these changes

2024-05-28 06:05 UTC, VladimirLQA approved these changes

2024-05-28 14:14 UTC, merged