HW 6 JS Arrays
limur88/automation_js-aqa_AV pull request #5
Opened 2024-06-06 16:22 UTC by limur88

2024-06-06 16:39 UTC, anatoly-karpovich requested changes

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task1.js
> +    answer.push(wages[index]);
```suggestion
    const index = employees.indexOf(name)
    if (index == -1){
        return "null"
    } else{
    const answer = [name,  wages[index]];
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +    }return unique
```suggestion
    } 
return unique.length ? unique : null
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +    let unique = [...my];
Checks for that task should be case insensitive

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +    for (let word of words){
```suggestion
    for (const word of words){
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +    for (let word of words){
```suggestion
    for (const word of words){
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +        if (word.length == 4){
```suggestion
        if (word.length == greatest){
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +    return answer
```suggestion
return count == word.length
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +console.log(checkIfPolyndrom ('Anna'))
```suggestion
console.log(`Word is palindrom: ${checkIfPolyndrom ('Anna')}`)
```

2024-06-06 16:39 UTC, anatoly-karpovich commented on Arrays-6/task3.js
> +    let digits = num.toString().split("");
```suggestion
    const digits = num.toString().split("");
```

2024-06-08 18:08 UTC, VladimirLQA submitted a review, later dismissed

2024-06-10 00:38 UTC, anatoly-karpovich submitted a review, later dismissed

2024-06-10 00:38 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +}
```suggestion
const result = []
for(const num of numbers){
if(! result.includes(num)) result.push(num)
}
```

2024-06-10 00:38 UTC, anatoly-karpovich commented on Arrays-6/task2.js
> +let numbers = [1, 1, 1, 1, 5, 5, 10, 3, 8, 10, 1, 1, 1, 5, 5, 6, 9];
There is "function" word in a task, please follow requirements)

2024-06-10 16:06 UTC, anatoly-karpovich approved these changes

2024-06-10 16:09 UTC, VladimirLQA commented on Arrays-6/task3.js
> +function cutDoubles(str){
Try with this case `zzabc`

2024-06-10 16:13 UTC, VladimirLQA commented on Arrays-6/task3.js
> +function sumOfDigits(num){
Try  to add handling for negative numbers, for example, `-19`

2024-06-10 16:13 UTC, VladimirLQA approved these changes

2024-06-10 19:20 UTC, merged